name: QA L3 Assessment - Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps ${{ matrix.browser }}
        
    - name: Create downloads directory
      run: mkdir -p downloads
      
    - name: Run API tests
      run: npm run test:api
      
    - name: Run E2E tests
      run: npm run test:e2e -- --project=${{ matrix.browser }}
      
    - name: Run all tests
      if: matrix.browser == 'chromium'
      run: npm run test -- --project=chromium
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results.json
          test-results.xml
          screenshots/
          downloads/
        retention-days: 30
        
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30
        
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}
        path: screenshots/
        retention-days: 30
        
    - name: Upload invoice files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: invoice-files-${{ matrix.browser }}
        path: downloads/
        retention-days: 30

  parallel-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps
        
    - name: Create downloads directory
      run: mkdir -p downloads
      
    - name: Run tests in parallel
      run: npm run test:parallel
      
    - name: Upload parallel test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: parallel-test-results
        path: |
          playwright-report/
          test-results.json
          test-results.xml
          screenshots/
          downloads/
        retention-days: 30

  cross-browser-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps
        
    - name: Create downloads directory
      run: mkdir -p downloads
      
    - name: Run Chrome tests
      run: npm run test:chrome
      
    - name: Run Firefox tests
      run: npm run test:firefox
      
    - name: Upload cross-browser results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cross-browser-results
        path: |
          playwright-report/
          test-results.json
          test-results.xml
          screenshots/
          downloads/
        retention-days: 30
